export type NewKadrajinOtesiPost = {
  slug: string;
  title: string;
  dateLabel: string;
  publishedAt: string;
  seriesNumber: number;
  seriesLabel: string;
  description: string;
  ogImage: string;
  readingImage: string;
  readingImageAfterParagraph: number;
  readingImageClass: "wide" | "portrait" | "editorial";
  readingImageWidth: number;
  readingImageHeight: number;
};

export const newKadrajinOtesiPosts: readonly NewKadrajinOtesiPost[] = [
  {
    "slug": "bir-yere-ait-olmadan-da-yasanir-mi",
    "title": "Bir Yere Ait Olmadan da Yaşanır mı?",
    "dateLabel": "Ağustos 2026",
    "publishedAt": "2026-08-12",
    "seriesNumber": 9,
    "seriesLabel": "Kadrajın ötesi",
    "description": "Bazı yerlerde yaşarız. Bazı yerlerse bizde yaşamaya devam eder.",
    "ogImage": "/yansimalar/rastgele-kadraj/rk11.jpeg",
    "readingImage": "/yansimalar/rastgele-kadraj/rk11.jpeg",
    "readingImageAfterParagraph": 24,
    "readingImageClass": "wide",
    "readingImageWidth": 1260,
    "readingImageHeight": 1065
  },
  {
    "slug": "gec-kaldigimiz-seyler",
    "title": "Geç Kaldığımız Şeyler",
    "dateLabel": "Ağustos 2026",
    "publishedAt": "2026-08-11",
    "seriesNumber": 8,
    "seriesLabel": "Kadrajın ötesi",
    "description": "Hayat bazen geç kalmaz. Biz başlamayı erteleriz.",
    "ogImage": "/yansimalar/gunbatımı/gb9.jpeg",
    "readingImage": "/yansimalar/gunbatımı/gb9.jpeg",
    "readingImageAfterParagraph": 27,
    "readingImageClass": "wide",
    "readingImageWidth": 1600,
    "readingImageHeight": 1066
  },
  {
    "slug": "sessizligin-de-bir-sesi-var",
    "title": "Sessizliğin de Bir Sesi Var",
    "dateLabel": "Ağustos 2026",
    "publishedAt": "2026-08-10",
    "seriesNumber": 7,
    "seriesLabel": "Kadrajın ötesi",
    "description": "Bazen insanın ihtiyacı cevap değil, biraz gürültünün eksilmesidir.",
    "ogImage": "/yansimalar/can dostlarımız/dost1.jpg",
    "readingImage": "/yansimalar/can dostlarımız/dost1.jpg",
    "readingImageAfterParagraph": 23,
    "readingImageClass": "wide",
    "readingImageWidth": 4553,
    "readingImageHeight": 4000
  },
  {
    "slug": "ayni-yerden-baska-biri-olarak-gecmek",
    "title": "Aynı Yerden Başka Biri Olarak Geçmek",
    "dateLabel": "Ağustos 2026",
    "publishedAt": "2026-08-09",
    "seriesNumber": 6,
    "seriesLabel": "Kadrajın ötesi",
    "description": "Bazı yerlere yıllar sonra döneriz. Değişenin yer olduğunu sanırız.",
    "ogImage": "/yansimalar/bolu/bolu7.jpg",
    "readingImage": "/yansimalar/bolu/bolu7.jpg",
    "readingImageAfterParagraph": 14,
    "readingImageClass": "portrait",
    "readingImageWidth": 1350,
    "readingImageHeight": 2400
  },
  {
    "slug": "bazi-insanlar-fotografta-kalmaz",
    "title": "Bazı İnsanlar Fotoğrafta Kalmaz",
    "dateLabel": "Ağustos 2026",
    "publishedAt": "2026-08-08",
    "seriesNumber": 5,
    "seriesLabel": "Kadrajın ötesi",
    "description": "Hayatımızdan geçen herkes bir kare bırakmaz. Bazıları yalnızca bizde kalır.",
    "ogImage": "/yansimalar/gokceada/gokceada2.JPG",
    "readingImage": "/yansimalar/gokceada/gokceada2.JPG",
    "readingImageAfterParagraph": 17,
    "readingImageClass": "editorial",
    "readingImageWidth": 6000,
    "readingImageHeight": 4000
  }
];

export const newKadrajinOtesiBodies: Record<string, readonly string[]> = {
  "bir-yere-ait-olmadan-da-yasanir-mi": [
  "Uzun zamandır “Nerelisin?” sorusunun göründüğü kadar kolay bir soru olmadığını düşünüyorum.",
  "İnsan doğduğu yeri söyleyebilir. Büyüdüğü şehri söyleyebilir. Şu anda yaşadığı yeri de söyleyebilir.",
  "Ama bunların hiçbiri bazen insanın gerçekten nereye ait olduğunu anlatmaz.",
  "Çünkü yaş ilerledikçe insanın hayatına başka şehirler giriyor. Başka yollar, başka odalar, başka pencereler…",
  "Bir yerde işe gidiyorsun. Başka bir yerde birkaç yıl geçiriyorsun. Bir şehrin sokaklarını ezberliyorsun, sonra bir gün bavulunu toplayıp başka bir yere gidiyorsun.",
  "İlk zamanlarda yabancı olduğun yerler bir süre sonra günlük hayatının parçasına dönüşüyor.",
  "Marketin yerini öğreniyorsun.",
  "Hangi yoldan daha kısa gidildiğini öğreniyorsun.",
  "Güneşin hangi tepeden battığını, yağmurun hangi sokakta daha çok biriktiğini bile öğreniyorsun.",
  "Sonra tuhaf bir şey oluyor.",
  "Bir zamanlar yabancı olduğun yerden ayrılırken bu kez ona dönüp bakıyorsun.",
  "İnsan galiba yalnızca evlerde yaşamıyor.",
  "Biraz sokaklarda, biraz manzaralarda, biraz da geçtiği yollarda kalıyor.",
  "Ben bazı yerlere fotoğraf çekmek için gittim. Bazı yerlerde çalıştım. Bazılarından sadece geçtim.",
  "Ama yıllar sonra fark ettim ki, insanın hafızası harita gibi çalışmıyor.",
  "Mesafeleri ölçmüyor.",
  "Bir yeri kilometresiyle değil, orada ne hissettiğinle hatırlıyorsun.",
  "Bazen yıllarca yaşadığın bir şehir sende birkaç görüntü bırakıyor.",
  "Bazen yalnızca birkaç saat bulunduğun bir yer, yıllar sonra bile bütün ayrıntılarıyla aklında kalıyor.",
  "Bir taş duvar.",
  "Denizin kokusu.",
  "Bir ağacın gölgesi.",
  "Yol kenarında içilen bir bardak çay.",
  "Bunların hangisinin “ev” olduğunu kim söyleyebilir?",
  "Belki de insanın evi, dönmek istediği yer değil; kendisi gibi olabildiği yerdir.",
  "İnsan yaş aldıkça kök salmanın yalnızca bir yerde uzun süre kalmak olmadığını anlıyor.",
  "Bazen kökler toprağa değil, hatıralara uzanıyor.",
  "Bir şehirden ayrılıyorsun ama oradaki bir akşam seninle geliyor.",
  "Bir sahilden uzaklaşıyorsun ama dalgaların sesi bir yerlerde kalıyor.",
  "Bir eve kapıyı son kez çekiyorsun; yıllar sonra o evin penceresinden giren sabah ışığını hâlâ hatırlıyorsun.",
  "Bu yüzden artık “ait olmak” kelimesini eskisi kadar kesin kullanamıyorum.",
  "Belki insan tek bir yere ait olmak zorunda değildir.",
  "Belki hayat boyunca geçtiğimiz yerlerin her birine küçük bir parçamızı bırakıyoruz.",
  "Onlardan da küçük bir şey alıp yolumuza devam ediyoruz.",
  "Sonra bütün bunların toplamına kendimiz diyoruz.",
  "Bazen uzun bir yolda yürürken bunu daha iyi anlıyorum.",
  "Arkamda bıraktığım yerlere bakıyorum.",
  "Önümde henüz görmediğim yollar var.",
  "İkisinin arasında duran kişi benim.",
  "Ne tamamen geride bıraktıklarıma aitim ne de henüz ulaşmadıklarıma.",
  "Ama bundan eskisi kadar rahatsız değilim.",
  "Çünkü insanın mutlaka bir yere ait olması gerekmiyor belki.",
  "Bazen yürümeye devam edebilmek de bir çeşit aidiyettir.",
  "Ve günün sonunda insanın yanında taşıdığı en gerçek memleket, kendisidir."
],
  "gec-kaldigimiz-seyler": [
  "İnsan hayatında kaç kere “daha önce yapsaydım” der bilmiyorum.",
  "Ama yaş ilerledikçe bu cümlenin sayısı artıyor.",
  "Daha önce başlasaydım.",
  "Daha önce gitseydim.",
  "Daha önce söyleseydim.",
  "Daha önce bıraksaydım.",
  "Daha önce cesaret etseydim.",
  "Sanki hayatın bir yerinde görünmeyen bir takvim varmış ve biz bazı tarihlere yetişememişiz gibi davranıyoruz.",
  "Oysa çoğu zaman geç kaldığımız şey hayat değil.",
  "Kendi kararımız.",
  "Yıllarca yapmak istediğimiz bir şeyi erteliyoruz.",
  "Şartlar düzelsin diyoruz.",
  "Para olsun.",
  "Vakit olsun.",
  "İşler sakinleşsin.",
  "Doğru insan çıksın.",
  "Doğru gün gelsin.",
  "Sonra fark ediyoruz ki hayat hiçbir zaman masayı tamamen temizleyip önümüze boş bir gün bırakmıyor.",
  "Bir sorun bitiyor, diğeri başlıyor.",
  "Bir telaş geçiyor, başka bir telaş geliyor.",
  "Ve biz yaşamayı sürekli daha uygun bir zamana erteliyoruz.",
  "Bence insanın kendisine yaptığı en büyük haksızlıklardan biri bu.",
  "Çünkü zaman biz hazır olana kadar beklemiyor.",
  "Ama bunun başka bir tarafı daha var.",
  "Bir şeye geç başladığımızı düşündüğümüzde bu kez tamamen vazgeçiyoruz.",
  "“Artık ne anlamı var?” diyoruz.",
  "İşte asıl kayıp orada başlıyor.",
  "Çünkü bazı şeylerin son kullanma tarihi yoktur.",
  "Yeni bir yol öğrenmenin yaşı yok.",
  "Bir yere ilk kez gitmenin yaşı yok.",
  "Bir fotoğraf makinesini eline alıp dünyaya başka türlü bakmanın yaşı yok.",
  "Yeni bir iş öğrenmenin, bir şey üretmenin, yeniden başlamanın da yaşı yok.",
  "İnsan bazen yirmisinde yapamadığını kırkında yapar.",
  "Ve belki de kırkında yaptığı için daha iyi anlar.",
  "Gençken zamanımız çoktur ama kendimizi az tanırız.",
  "Sonra zaman azalır fakat neyi istemediğimizi daha iyi biliriz.",
  "Bu küçümsenecek bir şey değildir.",
  "Hayatın ikinci yarısının avantajı da budur belki:",
  "Her kapıyı açmaya çalışmazsın.",
  "Hangisinin sana ait olduğunu biraz daha iyi seçersin.",
  "Geçmişe baktığımda benim de “keşke” dediğim şeyler var.",
  "Herkes gibi.",
  "Ama geçmişin karşısına geçip hesap sormanın insana fazla bir şey kazandırmadığını öğrendim.",
  "Çünkü geçmiş cevap vermiyor.",
  "Ne kadar sorarsan sor.",
  "Olanı değiştirmiyor.",
  "Fakat önünde hâlâ bir gün varsa sana başka bir imkân bırakıyor:",
  "Bugün başka türlü davranabilirsin.",
  "Bence umut tam olarak burada başlıyor.",
  "Büyük cümlelerde değil.",
  "“Bugün başlayabilirim” diyebilmekte.",
  "Bir gün batımını izlerken bunu sık sık düşünüyorum.",
  "Güneş birkaç dakika sonra kaybolacak diye kimse ona “geç kaldın” demiyor.",
  "O günün zamanı bitmiştir.",
  "Ama ertesi sabah başka bir yerden yeniden doğacaktır.",
  "İnsan hayatı elbette bu kadar basit değil.",
  "Kaybettiklerimiz geri gelmeyebilir.",
  "Bazı fırsatlar gerçekten bir kez gelir.",
  "Bazı insanların kapısını ikinci kez çalamayız.",
  "Bunu romantikleştirmenin anlamı yok.",
  "Ama bir şeyin bitmiş olması her şeyin bittiği anlamına da gelmez.",
  "Belki geçmişte başlayamadığın şeyi bugün başka biçimde başlatabilirsin.",
  "Belki gitmediğin yolun aynısını bulamazsın.",
  "Ama başka bir yol vardır.",
  "Hayat bize her zaman ikinci şans vermiyor.",
  "Fakat çoğu zaman başka bir şans veriyor.",
  "Aradaki farkı görmek gerekiyor.",
  "Bu yüzden artık “çok geç” cümlesini kolay söylememeye çalışıyorum.",
  "Saat gerçekten durmuşsa başka.",
  "Ama hâlâ sabah uyanıyorsan…",
  "Henüz anlatacağın birkaç hikâye daha vardır."
],
  "sessizligin-de-bir-sesi-var": [
  "Gün içinde ne kadar çok sese maruz kaldığımızı çoğu zaman fark etmiyoruz.",
  "Telefon.",
  "Mesajlar.",
  "Arabalar.",
  "İnsanlar.",
  "Bildirimler.",
  "Bir şey anlatanlar, bir şey isteyenler, bir yere yetişmeye çalışanlar…",
  "Bir süre sonra bütün bunlar hayatın normal sesi oluyor.",
  "Sonra bir gün şehirden biraz uzaklaşıyorsun.",
  "Telefon susuyor.",
  "Araba sesi kalmıyor.",
  "Karşında birkaç ağaç, uzakta tepeler ve nereden geldiğini bilmediğin bir kuş sesi.",
  "İlk birkaç dakika tuhaf geliyor.",
  "Çünkü insan gürültüye alışınca sessizlik bile yabancılaşıyor.",
  "Sonra yavaş yavaş başka sesleri fark etmeye başlıyorsun.",
  "Rüzgârın yaprakların arasından geçmesini.",
  "Toprağın üzerinde yürürken çıkan sesi.",
  "Uzakta bir köpeğin havlamasını.",
  "Kendi adımlarını.",
  "Hatta bazen kendi nefesini.",
  "O an anlıyorsun:",
  "Dünya aslında hiç susmamış.",
  "Biz çok gürültülü yaşamışız.",
  "Belki sessizlik dediğimiz şey, sesin yokluğu değil; gereksiz olanın çekilmesidir.",
  "Hayvanlarda sevdiğim bir taraf vardır.",
  "Yanında bulunmak için sürekli bir şey söylemek zorunda değillerdir.",
  "Bir köpek yanına gelir.",
  "Oturur.",
  "Bazen yüzüne bile bakmaz.",
  "Ama oradadır.",
  "İnsan ilişkilerinde ise sessizlik çoğu zaman doldurulması gereken bir boşluk kabul edilir.",
  "Konuşmalıyız.",
  "Bir şey anlatmalıyız.",
  "Bir fikir söylemeliyiz.",
  "Oysa bazı insanların yanında susabilmek, konuşabilmekten daha büyük bir yakınlıktır.",
  "Çünkü sessizlikte saklanacak fazla yer yoktur.",
  "İnsan kendisiyle de en çok böyle zamanlarda karşılaşıyor.",
  "Kalabalıkta düşüncelerden kaçmak kolay.",
  "Bir işle uğraşırsın.",
  "Telefona bakarsın.",
  "Birisiyle konuşursun.",
  "Bir şey açıp izlersin.",
  "Ama tek başına kaldığında bütün kaçış kapıları yavaş yavaş kapanır.",
  "Ve içeride ne varsa masaya oturur.",
  "Belki bu yüzden bazı insanlar yalnız kalmaktan hoşlanmaz.",
  "Çünkü sessizlik her zaman huzur getirmez.",
  "Bazen hesap getirir.",
  "Unuttuğunu düşündüğün şeyleri getirir.",
  "Kendine söylemediğin cümleleri getirir.",
  "Ama yine de kötü değildir.",
  "İnsan kendi sesini başka nasıl duyacak?",
  "Ben sessizliği artık boşluk olarak görmüyorum.",
  "Bir çeşit temizlik gibi görüyorum.",
  "Zihnin penceresini açmak gibi.",
  "Her şeyi çözmüyor.",
  "Bütün sorulara cevap vermiyor.",
  "Fakat hangisinin gerçekten önemli olduğunu ayırmaya yardım ediyor.",
  "Bazen uzun uzun düşünürsün ve hiçbir sonuç bulamazsın.",
  "Sonra bir ağacın altında oturursun.",
  "Bir bardak çay içersin.",
  "Hiçbir şey yapmazsın.",
  "Ve günlerdir kafanda dolaşan bir mesele birden küçülür.",
  "Çünkü bazı sorunların çözümü cevap bulmak değildir.",
  "Onları doğru büyüklükte görebilmektir.",
  "Sessizlik bunu yapıyor.",
  "Dünyayı susturmuyor.",
  "Sadece sesleri yeniden sıraya koyuyor.",
  "Belki insanın ara sıra ihtiyacı olan şey de budur.",
  "Hayattan kaçmak değil.",
  "Hayatın sesini biraz kısmak.",
  "Sonra yeniden dönmek.",
  "Ama bu kez kendi sesini de duyarak."
],
  "ayni-yerden-baska-biri-olarak-gecmek": [
  "Bir yere yıllar sonra yeniden gitmenin garip bir tarafı var.",
  "Yollar tanıdık geliyor.",
  "Binalardan bazıları hâlâ yerinde.",
  "Bir köşeyi dönünce ne çıkacağını biliyorsun.",
  "Ama yine de bir şey farklı.",
  "İlk başta şehrin değiştiğini düşünüyorsun.",
  "Yeni binalar yapılmış.",
  "Bazı dükkânlar kapanmış.",
  "Ağaçlar büyümüş.",
  "Sonra biraz daha dikkatli bakınca asıl değişenin yalnızca şehir olmadığını anlıyorsun.",
  "Sen de değişmişsin.",
  "Bir zamanlar önünden hiç düşünmeden geçtiğin bir yerde şimdi duruyorsun.",
  "Eskiden önemli bulduğun şeyler artık sana küçük geliyor.",
  "Hiç dikkat etmediğin ayrıntılar ise gözünden kaçmıyor.",
  "Aynı manzaraya bakarsın ama artık aynı gözlerle bakmıyorsundur.",
  "Belki bu yüzden bazı yerlere dönmek geçmişe dönmek değildir.",
  "İnsan geçmişe dönemez zaten.",
  "Sadece geçmişte bulunduğu bir yere bugünkü haliyle gider.",
  "Ve orada eski kendisinin izleriyle karşılaşır.",
  "Şurada yürümüştüm dersin.",
  "Burada oturmuştum.",
  "Şu yoldan her gün geçerdim.",
  "Ama o cümlelerin içindeki “ben” artık tam olarak sen değilsindir.",
  "İnsan bunu fark edince zamanın ne kadar sessiz çalıştığını anlıyor.",
  "Değişirken ses çıkarmıyoruz.",
  "Bir sabah kalkıp başka biri olmuyoruz.",
  "Gün gün değişiyoruz.",
  "Bir şey öğreniyoruz.",
  "Birinden vazgeçiyoruz.",
  "Birini kaybediyoruz.",
  "Bir karar alıyoruz.",
  "Bir hayal kuruyoruz.",
  "Bir hayalden vazgeçiyoruz.",
  "Ve bütün bunlar üst üste ekleniyor.",
  "Sonra yıllar sonra eski bir yere gittiğimizde aradaki mesafeyi birden görüyoruz.",
  "Bazen bir bardak çay yeter buna.",
  "Karşında yıllardır duran bir manzara vardır.",
  "Çay yine çaydır.",
  "Dağ yine oradadır.",
  "Göl yine aynı yerde.",
  "Ama masada oturan kişi başka biridir.",
  "Bence yaş almak biraz da bunu kabul etmektir.",
  "Eskiden olduğun kişiyi küçümsemeden ondan uzaklaşabilmek.",
  "“Nasıl böyle düşünmüşüm?” demek kolay.",
  "Ama o günkü insanın bildikleri o kadardı.",
  "Bugünkü aklımızla geçmişteki kendimizi yargılamak haksızlık.",
  "Çünkü bugün bildiklerimizi biraz da onun yaptığı hatalar sayesinde biliyoruz.",
  "Bu yüzden geçmişe baktığımda kendimle kavga etmek yerine anlamaya çalışıyorum.",
  "Her doğru karar beni buraya getirmedi.",
  "Bazı yanlış kararlar da getirdi.",
  "Bazı yollar uzundu.",
  "Bazıları gereksizdi.",
  "Bazılarından geri döndüm.",
  "Ama hepsi bugünkü bakışımın içinde bir yerde duruyor.",
  "Bir gün yeniden eski bir yere gidersen etrafına iyi bak.",
  "Nelerin değiştiğini gör.",
  "Sonra bir de kendine bak.",
  "Belki yıllardır aynı kaldığını düşündüğün birçok şeyin aslında çoktan değiştiğini fark edeceksin.",
  "Ve belki bunun kötü olmadığını da.",
  "Çünkü insanın bütün hayatı aynı kişi olarak geçirmesi, bana değişmekten daha korkutucu geliyor.",
  "Yollar aynı kalabilir.",
  "Dağlar aynı yerde durabilir.",
  "Aynı masada yeniden çay içebilirsin.",
  "Ama senin aynı kalmak gibi bir mecburiyetin yok."
],
  "bazi-insanlar-fotografta-kalmaz": [
  "Eski fotoğraflara bakarken bazen fotoğraftaki insanlardan çok, fotoğrafta olmayanları düşünüyorum.",
  "O gün orada olup kadraja girmeyenleri.",
  "Fotoğrafı çeken kişiyi.",
  "Biraz önce masadan kalkanı.",
  "Bir yolculukta birkaç saat konuşup sonra bir daha hiç görmediğimiz birini.",
  "Hayatımızdan geçen herkesin fotoğrafı yok.",
  "Ama bu, onların iz bırakmadığı anlamına gelmiyor.",
  "Bazı insanlarla yüzlerce fotoğrafımız vardır ve yıllar sonra baktığımızda fazla bir şey hissetmeyiz.",
  "Bazılarıyla ise tek kare bile yoktur.",
  "Ama söylediği bir cümleyi hatırlarız.",
  "Gülüşünü.",
  "Yürüyüşünü.",
  "Bir akşam yanımızda sessizce oturuşunu.",
  "İnsan hafızası tuhaf.",
  "Neyi saklayacağına bize sormuyor.",
  "Bazen çok önemli sandığımız şeyleri siliyor.",
  "Önemsiz sandığımız küçücük bir ayrıntıyı ise yıllarca taşıyor.",
  "İnsan bazen birini yüzüyle değil, yanında nasıl hissettiğiyle hatırlıyor.",
  "Hayatımıza giren herkes kalmak için gelmiyor.",
  "Bunu kabul etmek uzun zaman alıyor.",
  "İnsan gençken ilişkileri daha kesin düşünüyor.",
  "Gelen kalacak.",
  "Seven gitmeyecek.",
  "Dostluklar bozulmayacak.",
  "Verilen sözler tutulacak.",
  "Sonra hayat bunun böyle işlemediğini öğretiyor.",
  "Bazı insanlar bir dönem geliyor.",
  "Seninle aynı yolu yürüyor.",
  "Sonra yollar ayrılıyor.",
  "Bazen kavga ederek.",
  "Bazen hiçbir şey olmadan.",
  "İki taraf da kötü olmadığı halde.",
  "Hayat yalnızca başka yönlere aktığı için.",
  "Eskiden her gidişin bir sebebi olması gerektiğini düşünürdüm.",
  "Şimdi bundan o kadar emin değilim.",
  "Bazen sebep yoktur.",
  "Zaman vardır.",
  "Mesafe vardır.",
  "Değişen hayatlar vardır.",
  "İnsanların öncelikleri vardır.",
  "Ve bazen iki insanın hikâyesi yalnızca belli bir yere kadar birlikte yazılmıştır.",
  "Bunu kabul etmek, yaşananları değersizleştirmiyor.",
  "Tam tersine bana daha gerçek geliyor.",
  "Bir insan hayatında sonsuza kadar kalmadı diye onunla yaşadığın güzel bir gün neden değersiz olsun?",
  "Bir yolculuk bitti diye manzara kötüleşmez.",
  "Bir akşam sona erdi diye o akşam yaşanmamış olmaz.",
  "Belki ilişkiler konusunda yaptığımız en büyük hata, değerlerini süreleriyle ölçmek.",
  "Oysa bazı insanlar hayatımızda on yıl kalır ve bize hiçbir şey katmaz.",
  "Bazıları birkaç ay kalır ve dünyaya bakışımızda küçük bir pencere açar.",
  "Bazılarıysa yalnızca birkaç saat.",
  "Bir otobüste.",
  "Bir sahilde.",
  "Bir iş yerinde.",
  "Bir çay masasında.",
  "Sonra giderler.",
  "Adlarını bile yıllar sonra unutabiliriz.",
  "Ama o gün söyledikleri bir cümle kalır.",
  "Fotoğraf çekerken kadrajın dışında kalan şeyleri düşünürüm bazen.",
  "Makine yalnızca karşısındaki alanı kaydeder.",
  "Sağ tarafta ne olduğunu bilmez.",
  "Arkamızda kimin durduğunu bilmez.",
  "Fotoğraf çekildikten beş dakika sonra ne olduğunu da bilmez.",
  "Oysa hayat tam da oralarda devam eder.",
  "Kadrajın dışında.",
  "Belki insanlar da biraz böyledir.",
  "Hayatımızdan çıktıklarında tamamen yok olmazlar.",
  "Bir davranışımızda kalırlar.",
  "Bir kelimemizde.",
  "Dinlediğimiz bir şarkıda.",
  "Gitmekten hoşlandığımız bir yerde.",
  "Bazen hiç beklemediğimiz bir anda aklımıza düşerler.",
  "Sonra yine giderler.",
  "Artık bununla kavga etmiyorum.",
  "Her insanın hayatımda kalması gerekmiyor.",
  "Bazıları geldi.",
  "Bir süre yürüdü.",
  "Sonra kendi yoluna gitti.",
  "Ben de benimkine.",
  "Ama yolların bir zamanlar kesişmiş olması bile bazen yeter.",
  "Çünkü hayat yalnızca yanımızda kalanlardan oluşmuyor.",
  "Bizden geçenlerden de oluşuyor.",
  "Ve bazı insanlar hiçbir fotoğrafta görünmese bile hikâyenin içindedir."
],
};
